/* GENERATED by scripts/build-bases.mjs. Do not edit by hand. */

export type BaseColorId = "obsidian" | "neutral" | "zinc" | "slate" | "stone" | "gray"

export type BaseSwatch = {
  background: string
  surface: string
  foreground: string
  border: string
  muted: string
  /** Neutral solid fill (default solid button). */
  solid: string
}

export type BaseColor = { id: BaseColorId; label: string; description: string; light: BaseSwatch; dark: BaseSwatch }

/** Values for `data-glin-base`. Obsidian is the default and matches theme.css. */
export const baseColors: readonly BaseColor[] = [
  { id: "obsidian", label: "Obsidian", description: "Default theauth tones, cool and tonal.", light: { background: "oklch(0.985 0.002 240)", surface: "oklch(0.997 0.002 245)", foreground: "oklch(0.23 0.01 248)", border: "oklch(0.89 0.01 246)", muted: "oklch(0.52 0.014 270)", solid: "oklch(0.168 0.004 264)" }, dark: { background: "oklch(0.168 0.004 264.4)", surface: "oklch(0.198 0.004 229)", foreground: "oklch(0.95 0.01 247)", border: "oklch(0.323 0.009 248.1)", muted: "oklch(0.646 0.013 286)", solid: "oklch(0.96 0.004 247)" } },
  { id: "neutral", label: "Neutral", description: "Pure gray, no tint.", light: { background: "oklch(0.985 0 0)", surface: "oklch(0.997 0 0)", foreground: "oklch(0.21 0 0)", border: "oklch(0.89 0 0)", muted: "oklch(0.5 0 0)", solid: "oklch(0.19 0 0)" }, dark: { background: "oklch(0.16 0 0)", surface: "oklch(0.195 0 0)", foreground: "oklch(0.96 0 0)", border: "oklch(0.32 0 0)", muted: "oklch(0.7 0 0)", solid: "oklch(0.96 0 0)" } },
  { id: "zinc", label: "Zinc", description: "Cool, barely blue gray.", light: { background: "oklch(0.985 0.003 286)", surface: "oklch(0.997 0.0014 286)", foreground: "oklch(0.21 0.0108 286)", border: "oklch(0.89 0.0096 286)", muted: "oklch(0.5 0.0102 286)", solid: "oklch(0.19 0.0096 286)" }, dark: { background: "oklch(0.16 0.006 286)", surface: "oklch(0.195 0.0066 286)", foreground: "oklch(0.96 0.0036 286)", border: "oklch(0.32 0.012 286)", muted: "oklch(0.7 0.0096 286)", solid: "oklch(0.96 0.0036 286)" } },
  { id: "slate", label: "Slate", description: "Cool blue gray.", light: { background: "oklch(0.985 0.01 255)", surface: "oklch(0.997 0.0048 255)", foreground: "oklch(0.21 0.036 255)", border: "oklch(0.89 0.032 255)", muted: "oklch(0.5 0.034 255)", solid: "oklch(0.19 0.032 255)" }, dark: { background: "oklch(0.16 0.02 255)", surface: "oklch(0.195 0.022 255)", foreground: "oklch(0.96 0.012 255)", border: "oklch(0.32 0.04 255)", muted: "oklch(0.7 0.032 255)", solid: "oklch(0.96 0.012 255)" } },
  { id: "stone", label: "Stone", description: "Warm gray.", light: { background: "oklch(0.985 0.004 70)", surface: "oklch(0.997 0.0019 70)", foreground: "oklch(0.21 0.0144 70)", border: "oklch(0.89 0.0128 70)", muted: "oklch(0.5 0.0136 70)", solid: "oklch(0.19 0.0128 70)" }, dark: { background: "oklch(0.16 0.008 70)", surface: "oklch(0.195 0.0088 70)", foreground: "oklch(0.96 0.0048 70)", border: "oklch(0.32 0.016 70)", muted: "oklch(0.7 0.0128 70)", solid: "oklch(0.96 0.0048 70)" } },
  { id: "gray", label: "Gray", description: "Neutral blue-leaning gray.", light: { background: "oklch(0.985 0.005 260)", surface: "oklch(0.997 0.0024 260)", foreground: "oklch(0.21 0.018 260)", border: "oklch(0.89 0.016 260)", muted: "oklch(0.5 0.017 260)", solid: "oklch(0.19 0.016 260)" }, dark: { background: "oklch(0.16 0.01 260)", surface: "oklch(0.195 0.011 260)", foreground: "oklch(0.96 0.006 260)", border: "oklch(0.32 0.02 260)", muted: "oklch(0.7 0.016 260)", solid: "oklch(0.96 0.006 260)" } }
]
