/** Plain data for the components added in the 2026 expansion. No JSX so it is safe to import anywhere. */

export const newComponentIds = [
  "collapsible",
  "breadcrumb",
  "pagination",
  "navigation-menu",
  "menubar",
  "context-menu",
  "toggle",
  "toggle-group",
  "button-group",
  "input-group",
  "input-otp",
  "field",
  "combobox",
  "scroll-area",
  "aspect-ratio",
  "spinner",
  "empty",
  "item",
  "sidebar",
  "message",
  "bubble",
  "message-scroller",
  "prompt-input",
  "attachment",
  "thinking",
  "streaming-text",
  "questionnaire",
  "copy-button",
  "code-panel",
  "install-command",
  "reveal",
  "split-text",
  "count-up",
  "stagger-list",
  "hyper-text",
  "morphing-text",
  "sparkles-text",
  "gradient-text",
  "shine-border",
  "magic-card",
  "neon-gradient-card",
  "bento-grid",
  "light-rays",
  "grid-pattern",
  "animated-beam",
  "flickering-grid",
  "interactive-hover-button",
  "generate-button",
  "browser-frame",
  "terminal",
  "hero-section",
  "pricing-section",
  "logo-cloud",
  "feature-grid",
  "testimonials-wall",
  "faq-section",
  "cta-band",
  "footer-block",
  "cylinder-carousel",
  "image-comparison",
  "circular-gallery",
  "highlight-grid",
  "gooey-text-reveal",
  "spinning-text",
  "border-trail",
  "progressive-blur"
] as const

export type NewComponentId = (typeof newComponentIds)[number]

/** The AI / chat set, surfaced as its own sidebar, palette and gallery group. */
export const aiComponentIds = [
  "message",
  "bubble",
  "message-scroller",
  "prompt-input",
  "attachment",
  "thinking",
  "streaming-text",
  "questionnaire"
] as const satisfies readonly NewComponentId[]

export type AiComponentId = (typeof aiComponentIds)[number]

export const newComponentCopy: Record<NewComponentId, { title: string; description: string }> = {
  "collapsible": { title: "Collapsible", description: "Interactive panel that expands and collapses a region of content." },
  "breadcrumb": { title: "Breadcrumb", description: "Navigation trail showing the current page location in a hierarchy." },
  "pagination": { title: "Pagination", description: "Page navigation with previous, next and numbered links." },
  "navigation-menu": { title: "Navigation Menu", description: "Site navigation with animated dropdown content in a shared viewport." },
  "menubar": { title: "Menubar", description: "Desktop style horizontal menu bar with keyboard navigation." },
  "context-menu": { title: "Context Menu", description: "Right click menu with items, checkboxes, radios and submenus." },
  "toggle": { title: "Toggle", description: "A two-state button that can be pressed on or off." },
  "toggle-group": { title: "Toggle Group", description: "A set of toggles with single or multiple selection and merged segmented borders." },
  "button-group": { title: "Button Group", description: "Merges adjacent buttons into one segmented control with shared borders." },
  "input-group": { title: "Input Group", description: "An input with inline or block addons such as icons, text and buttons in one shared container." },
  "input-otp": { title: "Input OTP", description: "A one-time-code input with segmented slots, paste and autofill support." },
  "field": { title: "Field", description: "Accessible form field layout that wires labels, descriptions and errors to a control." },
  "combobox": { title: "Combobox", description: "A searchable select built from Popover and Command." },
  "scroll-area": { title: "Scroll Area", description: "Custom-styled scroll container with vertical and horizontal scrollbars that keeps native scrolling." },
  "aspect-ratio": { title: "Aspect Ratio", description: "Constrains content to a width to height ratio with optional surface frame." },
  "spinner": { title: "Spinner", description: "Accessible loading indicator with a reduced-motion pulsing ring fallback." },
  "empty": { title: "Empty", description: "Empty state with media, title, description, and action slots." },
  "item": { title: "Item", description: "Flexible list row with media, content, actions, header, and footer slots." },
  "sidebar": { title: "Sidebar", description: "Collapsible app sidebar with icon rail, mobile sheet, Ctrl/Cmd+B shortcut, and persisted state." },
  "reveal": { title: "Reveal", description: "In-view fade, blur and slide reveal that renders through the selected animation engine (css, motion or gsap)." },
  "split-text": { title: "Split Text", description: "Word or character reveal that keeps the full text accessible, driven by the selected animation engine." },
  "count-up": { title: "Count Up", description: "Number that counts to its final value in view, with a stable layout and an accessible final value." },
  "stagger-list": { title: "Stagger List", description: "Reveals direct children in sequence with a configurable order, driven by the selected animation engine." },
  "message": { title: "Message", description: "Chat turn layout with roles, avatar, bubble content and an actions toolbar (copy, regenerate, feedback)." },
  "bubble": { title: "Bubble", description: "Chat bubble surface with default, muted, accent and glass variants, optional tail and grouped spacing." },
  "message-scroller": { title: "Message Scroller", description: "Conversation log that sticks to the bottom, shows a jump to latest pill and announces new messages politely." },
  "prompt-input": { title: "Prompt Input", description: "Auto-growing chat composer with send and stop, IME-safe Enter handling, attachment slot and character hint." },
  "attachment": { title: "Attachment", description: "File chip or image thumbnail with type icon, size, upload progress and remove button." },
  "thinking": { title: "Thinking", description: "Reasoning indicator with animated dots or pulsing text and collapsible reasoning details." },
  "streaming-text": { title: "Streaming Text", description: "Progressive text reveal with caret and completion callback, instant under reduced motion." },
  "questionnaire": { title: "Questionnaire", description: "Multi-step form with single and multiple choice option cards, progress and keyboard accessible radio and checkbox semantics." },
  "copy-button": { title: "Copy Button", description: "Raised pill that copies text, announces the result and resets after 1.6 seconds." },
  "code-panel": { title: "Code Panel", description: "Raised header bar over an inset code well with tok-k, tok-s, tok-c and tok-f token classes." },
  "install-command": { title: "Install Command", description: "Package manager tabs, a $ prefixed command and a copy button inside a code panel." },
  "hyper-text": { title: "Hyper Text", description: "Text that scrambles through random characters and settles on the real string, on hover, in view or on mount." },
  "morphing-text": { title: "Morphing Text", description: "Cycles through words with a gooey blur and threshold morph, paused off screen and static under reduced motion." },
  "sparkles-text": { title: "Sparkles Text", description: "Text with twinkling star sparkles that scale and rotate, with a static accent under reduced motion." },
  "gradient-text": { title: "Gradient Text", description: "Flowing gradient or shine sweep text, optionally inside a solid or glass pill badge." },
  "shine-border": { title: "Shine Border", description: "Animated gradient edge that wraps any rounded container." },
  "magic-card": { title: "Magic Card", description: "Card whose border and surface light up under the pointer or keyboard focus." },
  "neon-gradient-card": { title: "Neon Gradient Card", description: "Card with an animated neon gradient ring and soft glow." },
  "bento-grid": { title: "Bento Grid", description: "Responsive bento layout of linked feature tiles." },
  "light-rays": { title: "Light Rays", description: "Soft swaying rays of light for hero and section backgrounds." },
  "grid-pattern": { title: "Grid Pattern", description: "SVG grid, stripes and interactive cell patterns with edge fades." },
  "animated-beam": { title: "Animated Beam", description: "A gradient beam that travels between two elements." },
  "flickering-grid": { title: "Flickering Grid", description: "Canvas grid of squares that flicker, with token colors and a static fallback." },
  "interactive-hover-button": { title: "Interactive Hover Button", description: "Pill button whose accent dot floods the surface on hover, focus or press." },
  "generate-button": { title: "Generate Button", description: "AI style call to action with idle, generating and loading states." },
  "browser-frame": { title: "Browser Frame", description: "Generic browser window chrome drawn in CSS with a slot for any content." },
  "terminal": { title: "Terminal", description: "Terminal window with sequenced typing and output, a full transcript and copy." },
  "hero-section": { title: "Hero Section", description: "Landing hero with announcement pill, actions, media slot and logo strip in centered, split and stacked layouts." },
  "pricing-section": { title: "Pricing Section", description: "Tier cards with monthly or yearly switch, highlighted plan, check lists and a comparison table layout." },
  "logo-cloud": { title: "Logo Cloud", description: "Grayscale-to-color logo strip with a marquee option that respects reduced motion." },
  "feature-grid": { title: "Feature Grid", description: "Icon-framed feature cards in three-up, bento, icon-list and alternating-row layouts." },
  "testimonials-wall": { title: "Testimonials Wall", description: "Social proof as masonry columns, vertical marquee columns or a single featured quote." },
  "faq-section": { title: "FAQ Section", description: "Accordion based FAQ with two column or centered layout, category tabs and a FAQPage JSON-LD helper." },
  "cta-band": { title: "CTA Band", description: "Closing call to action: centered, split with email capture, or boxed with a token glow." },
  "footer-block": { title: "Footer Block", description: "Site footer with link groups, brand and newsletter slots, social icons, legal row and theme toggle slot." },
  "cylinder-carousel": { title: "Cylinder Carousel", description: "Slides on a rotating 3D ring with buttons, arrow keys, swipe and a pausable autoplay." },
  "image-comparison": { title: "Image Comparison", description: "Before and after layers split by a draggable, keyboard operable slider handle." },
  "circular-gallery": { title: "Circular Gallery", description: "Tiles on a ring that rotates to the front with drag inertia, keys, click and optional autorotate." },
  "highlight-grid": { title: "Highlight Grid", description: "Hairline cell grid with one shared highlight that glides to the hovered, tapped or focused cell." },
  "gooey-text-reveal": { title: "Gooey Text Reveal", description: "Heading whose words melt in through a shared SVG goo filter, or morph between phrases." },
  "spinning-text": { title: "Spinning Text", description: "Text laid out on a rotating circle with an accessible name and pause on hover." },
  "border-trail": { title: "Border Trail", description: "Glowing comet that travels along the border of a rounded container." },
  "progressive-blur": { title: "Progressive Blur", description: "Edge overlay that blurs content progressively using stacked masked backdrop filters." }
}
