/**
 * Per-component defaults for the docs preview stage: which backdrop the stage opens on and how tall it is.
 * Effect components read best on a dark or photo stage (spotlight, glow, beams); glass needs a rich backdrop.
 * Each showcase agent owns one clearly marked block below: add one line per component id.
 */
export type StageBackdrop = "mesh" | "light" | "dark" | "vivid" | "photo"
export type StageHeight = "sm" | "md" | "lg"

export type StageDefault = {
  backdrop?: StageBackdrop
  size?: StageHeight
}

const stageDefaults: Record<string, StageDefault> = {
  // S1 (buttons, forms and inputs)
  "shimmer-button": { backdrop: "dark", size: "md" },
  "ripple-button": { backdrop: "mesh", size: "md" },
  "pulsating-button": { backdrop: "dark", size: "md" },
  "liquid-button": { backdrop: "vivid", size: "md" },
  "magnetic-cta": { backdrop: "mesh", size: "lg" },
  "glass-toggle": { backdrop: "photo", size: "lg" },
  "generate-button": { backdrop: "mesh", size: "md" },
  "button-group": { size: "md" },
  input: { size: "lg" },
  field: { size: "lg" },
  "input-otp": { size: "md" },
  combobox: { size: "lg" },
  select: { size: "lg" },
  slider: { size: "md" },
  switch: { size: "lg" },
  "prompt-input": { size: "lg" },
  // S2 (navigation, overlays and menus)
  "navigation-menu": { backdrop: "mesh", size: "lg" },
  "menubar": { backdrop: "mesh", size: "lg" },
  "tabs": { backdrop: "mesh", size: "md" },
  "breadcrumb": { backdrop: "mesh", size: "md" },
  "sidebar": { backdrop: "mesh", size: "lg" },
  "pagination": { backdrop: "mesh", size: "md" },
  "link": { backdrop: "mesh", size: "md" },
  "modal": { backdrop: "mesh", size: "md" },
  "alert-dialog": { backdrop: "mesh", size: "md" },
  "sheet": { backdrop: "mesh", size: "lg" },
  "popover": { backdrop: "mesh", size: "lg" },
  "hover-card": { backdrop: "mesh", size: "lg" },
  "tooltip": { backdrop: "mesh", size: "md" },
  "dropdown-menu": { backdrop: "mesh", size: "lg" },
  "context-menu": { backdrop: "mesh", size: "md" },
  "command": { backdrop: "mesh", size: "md" },
  // S3 (feedback, data display, layout)
  alert: { backdrop: "mesh", size: "lg" },
  progress: { backdrop: "mesh", size: "lg" },
  skeleton: { backdrop: "mesh", size: "lg" },
  spinner: { backdrop: "mesh", size: "md" },
  "status-dot": { backdrop: "mesh", size: "md" },
  empty: { backdrop: "mesh", size: "md" },
  badge: { backdrop: "mesh", size: "lg" },
  chip: { backdrop: "mesh", size: "md" },
  avatar: { backdrop: "mesh", size: "md" },
  table: { backdrop: "mesh", size: "lg" },
  "data-table": { backdrop: "mesh", size: "lg" },
  tree: { backdrop: "mesh", size: "md" },
  counter: { backdrop: "mesh", size: "md" },
  kbd: { backdrop: "mesh", size: "lg" },
  item: { backdrop: "mesh", size: "lg" },
  "scroll-area": { backdrop: "mesh", size: "lg" },
  "aspect-ratio": { backdrop: "mesh", size: "lg" },
  collapsible: { backdrop: "mesh", size: "md" },
  separator: { backdrop: "mesh", size: "md" },
  "icon-frame": { backdrop: "mesh", size: "md" },
  accordion: { backdrop: "mesh", size: "lg" },
  "browser-frame": { backdrop: "mesh", size: "lg" },
  // S4 (backgrounds, text and code, AI)
  "aurora-background": { backdrop: "dark", size: "lg" },
  "gradient-mesh": { backdrop: "dark", size: "lg" },
  "light-leak": { backdrop: "dark", size: "lg" },
  "light-rays": { backdrop: "dark", size: "lg" },
  "grid-pattern": { backdrop: "dark", size: "lg" },
  "dot-pattern": { backdrop: "dark", size: "lg" },
  "flickering-grid": { backdrop: "dark", size: "lg" },
  "retro-grid": { backdrop: "dark", size: "lg" },
  "particle-field": { backdrop: "dark", size: "lg" },
  "meteor-shower": { backdrop: "dark", size: "lg" },
  "orbiting-circles": { backdrop: "dark", size: "lg" },
  "animated-gradient": { backdrop: "dark", size: "lg" },
  "chromatic-text": { backdrop: "dark", size: "lg" },
  "gradient-text": { backdrop: "dark", size: "lg" },
  "code-panel": { size: "lg" },
  "message": { size: "lg" },
  "bubble": { size: "lg" },
  "message-scroller": { size: "lg" },
  "attachment": { size: "lg" },
  "thinking": { size: "lg" },
  "streaming-text": { size: "lg" },
  "questionnaire": { size: "lg" },
  "heading": { size: "lg" },
  // Signature heroes (glass and floating surfaces read best on rich backdrops)
  "glass-navbar": { backdrop: "vivid", size: "lg" },
  "glass-dock": { backdrop: "photo", size: "lg" },
  "glass-breadcrumb": { backdrop: "vivid", size: "md" },
  "morphing-tabs": { backdrop: "mesh", size: "md" },
  "floating-panel": { backdrop: "mesh", size: "lg" },
  "toast": { backdrop: "mesh", size: "lg" },
  // S5 (motion and engine-aware animated components)
  "word-rotate": { backdrop: "mesh", size: "md" },
  "number-ticker": { backdrop: "light", size: "lg" },
  "marquee": { backdrop: "light", size: "lg" },
  "blur-fade": { backdrop: "light", size: "lg" },
  "typewriter": { backdrop: "dark", size: "md" },
  "terminal": { backdrop: "dark", size: "lg" },
  "shine-border": { backdrop: "dark", size: "md" },
  "border-beam": { backdrop: "dark", size: "md" },
  "animated-beam": { backdrop: "light", size: "lg" },
  "bento-grid": { backdrop: "mesh", size: "lg" },
  "sparkles-text": { backdrop: "dark", size: "md" },
  "morphing-text": { backdrop: "dark", size: "md" },
  "hyper-text": { backdrop: "dark", size: "md" },
  "text-reveal": { backdrop: "light", size: "md" },
  "reveal-text": { backdrop: "mesh", size: "md" },
  "reveal": { backdrop: "mesh", size: "md" },
  "split-text": { backdrop: "mesh", size: "md" },
  "count-up": { backdrop: "light", size: "lg" },
  "stagger-list": { backdrop: "mesh", size: "md" },
  // S6 (batch B: blocks, media and edge effects)
  "hero-section": { backdrop: "mesh", size: "lg" },
  "pricing-section": { backdrop: "mesh", size: "lg" },
  "logo-cloud": { backdrop: "mesh", size: "lg" },
  "feature-grid": { backdrop: "mesh", size: "lg" },
  "testimonials-wall": { backdrop: "mesh", size: "lg" },
  "faq-section": { backdrop: "mesh", size: "lg" },
  "cta-band": { backdrop: "mesh", size: "lg" },
  "footer-block": { backdrop: "mesh", size: "lg" },
  "cylinder-carousel": { backdrop: "dark", size: "lg" },
  "circular-gallery": { backdrop: "dark", size: "lg" },
  "image-comparison": { backdrop: "dark", size: "lg" },
  "progressive-blur": { backdrop: "dark", size: "lg" },
  "highlight-grid": { backdrop: "mesh", size: "lg" },
  "gooey-text-reveal": { backdrop: "dark", size: "md" },
  "spinning-text": { backdrop: "dark", size: "md" },
  "border-trail": { backdrop: "dark", size: "md" },
}

export function getStageDefault(id: string | undefined): StageDefault | undefined {
  return id ? stageDefaults[id] : undefined
}
